# Generated by Django 5.2.7 on 2026-01-31 17:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_transaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='lead_time_days',
            field=models.IntegerField(default=7, help_text='Days required to restock this item'),
        ),
        migrations.AddField(
            model_name='item',
            name='reorder_level',
            field=models.IntegerField(default=10, help_text='Minimum stock level before reorder suggestion'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(choices=[('KHALTI', 'Khalti'), ('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer'), ('CREDIT', 'Credit')], default='KHALTI', max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_reference',
            field=models.CharField(blank=True, help_text='Payment gateway reference ID', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_status',
            field=models.CharField(choices=[('PAID', 'Paid'), ('PENDING', 'Pending'), ('FAILED', 'Failed')], default='PENDING', max_length=10),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['payment_status'], name='inventory_t_payment_0b81ee_idx'),
        ),
    ]
