# Generated by Django 5.2.7 on 2026-02-16 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_item_lead_time_days_item_reorder_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload product image (optional)', null=True, upload_to='products/'),
        ),
    ]
