# Generated by Django 5.2.7 on 2026-02-22 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(choices=[('KHALTI', 'Khalti'), ('ESEWA', 'eSewa'), ('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer'), ('CREDIT', 'Credit')], default='KHALTI', max_length=20),
        ),
    ]
