# Generated by Django 5.2.7 on 2026-03-03 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_customer_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cost price per unit', max_digits=10),
        ),
    ]
